---
- hosts: all
  become: yes

  tasks:
    - name: upgrade all packages
      yum: name='*' state=latest

    - name: Install Apache.
      yum: name={{ item }} state=present
      with_items:
         - epel-release
         - httpd
         - httpd-devel

    - name: Stop and disable firewalld only for test.
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Create the directory structure for site.
      file: path=/var/www/ditelkin.com owner=root group=root mode=0755 recurse=yes state=directory

    - name: Create the second directory inside first.
      file: path=/var/www/ditelkin.com/public_html owner=root group=root mode=0755 recurse=yes state=directory

    - name: Copy demo pages for virtual host.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: apache
        group: apache
        mode: 0644
      with_items:
        - src: "index2.html"
          dest: "/var/www/ditelkin.com/public_html/index.html"

    - name: Make sure Apache is restarted.
      service: name=httpd state=restarted

    - name: Copy httpd config file.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "httpd.conf"
          dest: "/etc/httpd/conf/httpd.conf"

    - name: Make sure Apache is restarted.
      service: name=httpd state=restarted

    - name: Copy first virtual Host file.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "ditelkin.conf"
          dest: "/etc/httpd/conf.d/ditelkin.conf"

    - name: Make sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes