---
- hosts: all
  become: yes

  tasks:
    - name: Install Apache.
      yum: name={{ item }} state=present
      with_items:
         - httpd
         - httpd-devel

    - name: Copy demo pages for virtual host.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: apache
        group: apache
        mode: 0644
      with_items:
        - src: "index.html"
          dest: "/var/www/html/index.html"

    - name: Make sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes

