---
- hosts: all
  become: yes

  tasks:
    - name: Create the directory structure for site.
      file: path=/var/www/{{ item.0 }}/{{ item.1 }}/{{ item.2 }} owner=root group=root mode=0755 recurse=yes state=directory
      with_nested:
      - ['sites', 'sites', 'sites']
      - ['ditelkin1.com', 'ditelkin2.com', 'ditelkin3.com']
      - ['html', 'html', 'html']

    - name: Create folder for VHOST files
      file: path=/etc/httpd/{{ item }} owner=root group=root mode=0755 state=directory
      with_items:
        - ["sites-available", "sites-enabled"]
