---
- hosts: all
  become: yes

  tasks:
    - name: Create the directory structure for site.
      file: path=/var/www/{{ item }} state=absent
      with_items:
      - 'ditelkin1.com'
      - 'ditelkin2.com'
      - 'ditelkin3.com'
