---
- hosts: all
  become: yes

  tasks:
    - name: Copy demo pages for virtual host.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: apache
        group: apache
        mode: 0644
      with_items:
        - src: "index.html"
          dest: "/var/www/html/index.html"

    - name: Restarted Apache.
      service: name=httpd state=restarted